name: Build pipeline
trigger:
  branches:
    include:
    - main

stages:

- stage: build
  displayName: Build
  jobs:
  - template: .azure-pipeline-templates/.dotnet-build.yml

- stage: test
  displayName: Test
  jobs:
  - template: .azure-pipeline-templates/.dotnet-test.yml
    parameters:
      project: Tests.UnitTests
  - template: .azure-pipeline-templates/.dotnet-test.yml
    parameters:
      project: Tests.IntegrationTests
