name: Build pipeline
trigger:
  branches:
    include:
    - main

stages:

- stage: build
  displayName: Build
  jobs:
  - job: build
    pool:
      vmImage: ubuntu-latest
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build
      inputs:
        command: build
        buildContext: '.'
        Dockerfile: Host/Dockerfile

- stage: test
  displayName: Test
  jobs:
  - template: .azure-pipeline-templates/.dotnet-test.yml
    parameters:
      project: Tests.UnitTests
  - template: .azure-pipeline-templates/.dotnet-test.yml
    parameters:
      project: Tests.IntegrationTests
