parameters:
- name: sdk
  type: string
  default: '6.0'

steps:
- task: Cache@2
  inputs:
    key: 'nuget | "$(Agent.OS)" | **/packages.lock.json, !**/bin/**'
    restoreKeys: |
      nuget | "$(Agent.OS)"
    path: packages
  displayName: NuGet packages cache
- task: UseDotNet@2
  inputs:
    version: ${{ parameters.sdk }}.x
    includePreviewVersions: true
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    restoreArguments: --locked-mode
    packagesDirectory: packages
