parameters:
- name: sdk
  type: string
  default: '6.0'
- name: framework
  type: string
  default: 'net6.0'
- name: configuration
  type: string
  default: 'Release'
- name: project
  type: string
  default: '.'
  
jobs: 
  - job: tests_${{ replace(parameters['project'], '.', '_') }}
    pool:
      vmImage: ubuntu-latest
    displayName: ${{ parameters.project }}
    steps:
    - task: UseDotNet@2
      inputs:
        version: ${{ parameters.sdk }}.x
        includePreviewVersions: true
    - template: .dotnet-restore.yml
    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: test
        projects: ${{ parameters.project }}
        packagesDirectory: packages
        arguments: '--configuration ${{ parameters.configuration }} --framework ${{ parameters.framework }} --no-restore --test-adapter-path:. --logger:"nunit;LogFilePath=test-result.xml'
      continueOnError: 'true'
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: NUnit
        testResultsFiles: '**/test-result.xml'
        failTaskOnFailedTests: true