parameters:
- name: sdk
  type: string
  default: '6.0'
- name: framework
  type: string
  default: 'net6.0'
- name: project
  type: string
  default: '.'
  
jobs: 
  - job: tests_${{ replace(parameters['project'], '.', '_') }}
    pool:
      vmImage: ubuntu-latest
    displayName: ${{ parameters.project }}
    steps:
    - task: UseDotNet@2
      inputs:
        version: ${{ parameters.sdk }}.100-preview.7.21379.14
        includePreviewVersions: true
    - task: Cache@2
      inputs:
        key: 'nuget | "$(Agent.OS)" | **/packages.lock.json, !**/bin/**'
        restoreKeys: |
          nuget | "$(Agent.OS)"
        path: packages
      displayName: NuGet packages cache
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        restoreArguments: --locked-mode
        packagesDirectory: packages
    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: test
        projects: ${{ parameters.project }}
        packagesDirectory: packages
        arguments: '--framework ${{ parameters.framework }} --no-restore --test-adapter-path:. --logger:"\"nunit;LogFilePath=test-result.xml\"'
      continueOnError: 'true'
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: NUnit
        testResultsFiles: '**/test-result.xml'
        failTaskOnFailedTests: true
    - task: DotNetCoreCLI@2
      displayName: Code coverage
      inputs:
        command: test
        projects: ${{ parameters.project }}
        packagesDirectory: packages
        arguments: '--framework ${{ parameters.framework }} --no-build  --settings coverlet.runsettings --collect:"\"XPlat Code Coverage\"'
      continueOnError: true
    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: '$(Agent.TempDirectory)/*/coverage.cobertura.xml'
        failIfCoverageEmpty: true