name: Build
run-name: Build
on:
  pull_request:
  push:
    branches:
      - 'main'
jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        dotnet-version: ['7.0.x']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore --locked-mode
      - name: Build
        run: dotnet build --no-restore --configuration Release
      - name: Test
        run: dotnet test --no-restore --test-adapter-path:. --logger:"nunit;LogFilePath=test-result.xml"
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
          nunit_files: '**/test-result.xml'
      - name: Code coverage
        run: dotnet test --no-build --settings coverlet.runsettings --collect:"XPlat Code Coverage"
      - name: Publish code coverage results
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: '**/coverage.cobertura.xml'
          badge: true
          format: 'markdown'
          output: 'both'
      - name: Create code coverage result comment for pull request
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
      - name: Create code coverage result note for step summary
        run: |
          touch code-coverage-results-summary.md
          echo -e "\n## Code coverage\n" >> code-coverage-results-summary.md
          cat code-coverage-results.md >> code-coverage-results-summary.md
          cat code-coverage-results-summary.md
          cat code-coverage-results-summary.md >> $GITHUB_STEP_SUMMARY
